# Generated by Django 4.0.4 on 2024-05-02 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taxapp2.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('area_code', models.CharField(max_length=2)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lga')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(choices=[('supervisor1', 'Supervisor 1'), ('supervisor2', 'Supervisor 2'), ('ward_monitor', 'Ward Monitor'), ('tax_collector', 'Tax Collector')], default='supervisor1', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supervisor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_supervisor1', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_supervisor1_role])),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.state'),
        ),
        migrations.AddField(
            model_name='lga',
            name='supervisor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lga_supervisor2', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_supervisor2_role]),
        ),
        migrations.CreateModel(
            name='WardAndMonitor',
            fields=[
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.ward')),
                ('ward_monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_monitor', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_ward_monitor_role])),
            ],
        ),
    ]
