# Generated by Django 4.0.4 on 2024-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lga_ward_user_staff_role_state_lga_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='090', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(default='abc123', max_length=50),
            preserve_default=False,
        ),
    ]
