# Generated by Django 4.0.4 on 2024-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_lga_code_alter_ward_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(choices=[('supervisor1', 'SUPERVISOR/DIRECTOR'), ('supervisor2', 'LGA SUPERVISOR/MONITOR'), ('ward_monitor', 'WARD SUPERVISOR/MONITOR'), ('tax_collector', 'TAX COLLECTOR'), ('assessment_officer', 'ASSESSMENT OFFICER'), ('audit_officer', 'AUDIT OFFICER')], max_length=20),
        ),
    ]
