# Generated by Django 4.0.4 on 2024-05-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taxapp2.users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='supervisor2',
        ),
        migrations.RemoveField(
            model_name='state',
            name='supervisor1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='users.lga'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('supervisor1', 'SUPERVISOR/DIRECTOR'), ('supervisor2', 'LGA SUPERVISOR/MONITOR'), ('ward_monitor', 'WARD SUPERVISOR/MONITOR'), ('tax_collector', 'TAX COLLECTOR'), ('assessment_officer', 'ASSESSMENT OFFICER'), ('audit_officer', 'AUDIT OFFICER'), ('tax_payer', 'TAX PAYER')], default='supervisor1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Statesupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lga')),
                ('supervisor1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_supervisor', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_supervisor1_role])),
            ],
        ),
        migrations.CreateModel(
            name='LGAsupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lga')),
                ('supervisor2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lga_supervisor', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_supervisor2_role])),
            ],
        ),
    ]
