# Generated by Django 4.0.4 on 2024-05-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_lga_supervisor2_remove_state_supervisor1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_id',
        ),
    ]
