# Generated by Django 4.0.4 on 2024-06-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxarea',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards_in_taxArea', to='users.ward'),
        ),
    ]
