# Generated by Django 4.0.4 on 2024-06-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_taxarea_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_in_location', to='users.lga'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_in_ward', to='users.lga'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50),
        ),
    ]
