# Generated by Django 4.0.4 on 2024-06-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_location_alter_ward_lga_alter_ward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas_in_ward', to='users.lga'),
        ),
    ]
