# Generated by Django 4.0.4 on 2024-06-17 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taxapp2.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_ward_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_in_location', to='users.lga'),
        ),
        migrations.AlterField(
            model_name='wardandmonitor',
            name='ward_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_monitor', to=settings.AUTH_USER_MODEL, validators=[taxapp2.users.models.validate_ward_monitor_role]),
        ),
    ]
