# Generated by Django 4.0.4 on 2024-06-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardandmonitor',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.ward'),
        ),
    ]
