# Generated by Django 4.0.4 on 2024-06-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_staff_id'),
        ('taxpayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='anual_income',
            field=models.FloatField(default=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessuser',
            name='tax_area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user_tax_area', to='users.taxarea'),
        ),
    ]
