# Generated by Django 4.0.4 on 2024-06-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_staff_id'),
        ('taxpayer', '0003_businessuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='tax_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user_tax_area', to='users.taxarea'),
        ),
    ]
