# Generated by Django 4.0.4 on 2024-06-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayer', '0004_alter_businessuser_tax_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='status',
            field=models.CharField(choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed'), ('query', 'Query'), ('approved', 'Approved')], default='pending review', max_length=20),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_paid', models.FloatField(blank=True, null=True)),
                ('tax_due_time', models.CharField(blank=True, choices=[('annually', 'Annually'), ('monthly', 'Monthly'), ('daily', 'Daily')], max_length=20, null=True)),
                ('query', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payer_assesment', to='taxpayer.businessuser')),
            ],
        ),
    ]
