# Generated by Django 4.0.4 on 2024-06-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_wardandmonitor_ward'),
        ('taxpayer', '0006_remove_businessuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='ward',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxpayer_ward', to='users.ward'),
        ),
    ]
