# Generated by Django 4.0.4 on 2024-06-27 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayer', '0009_payment_app_fee_payment_auth_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
